python3 test1.py
python3 test1rms.py
python3 test1ada.py
python3 test2.py
python3 test2rms.py
python3 test2ada.py
python3 test3.py
python3 test3rms.py
python3 test3ada.py
python3 test4.py
python3 test4rms.py
python3 test4ada.py
python3 test5.py
python3 test5rms.py
python3 test5ada.py
python3 test6.py
python3 test6rms.py
python3 test6ada.py
python3 test7.py
python3 test7rms.py
python3 test7ada.py
python3 test8.py
python3 test8rms.py
python3 test8ada.py
python3 data_ADAGrad.py
python3 data_genetic_multi.py
python3 data_genetic.py
python3 data_gradient.py
python3 data_RMSProp.py
python3 eye_ADAGrad.py
python3 eye_genetic.py
python3 eye_gradient.py
python3 eye_RMSProp.py
